language: c
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - TARGET="linux"
  - os: osx
    osx_image: xcode8
    env:
    - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
    - TARGET="osx"
before_script:
- if [ "$TARGET" = "osx" ]; then brew update && brew install ruby && brew install
  rename; fi
- eval "${MATRIX_EVAL}"
script:
- if [ "$TARGET" = "linux" ]; then echo "===> Building for linux..." && cd "$TRAVIS_BUILD_DIR"
  && mkdir build && cd build && cmake .. && make; fi
- if [ "$TARGET" = "osx" ]; then echo "===> Building for macosx..." && cd "$TRAVIS_BUILD_DIR"
  && mkdir build && cd build && cmake .. && make; fi
- eval "rename 's/openfiledialog/openfiledialog-${TARGET}/' openfiledialog*"
- eval "rename 's/selectfolderdialog/selectfolderdialog-${TARGET}/' selectfolderdialog*"
deploy:
  provider: releases
  api_key:
    secure: YvLf0Mz9jhznO7UWfpsDWcPosgGTRgHkFlZOdtI8061f91Ar/ZJPkpZrzQt424vXAhnMjAijFg1Jz05/nFmNnrPXLnXM1NE9qAMVH/jHU0dgwPZTuAAW/DEX8x/XltNh+q8TVov2Ps34nw3QyYI4U1W8nPE1TPdbXWLDMRmHvuv9ULTxcvazKgYqy6fh5uelbOgecEImDQmjODexFKBtGL1iGCufUMC1yZ5IPvGhdHr7VU01p1WQeSFqJZ/T32kQeVrGeEL+bMQR4DBCoShQKJsidrYQAUQNSpABZMa01n/J8ir6KusSgfesXYiIob9rHrvM+BhcmgnzNBfmDBT6SLb2DOfcEoQTeZqk9tu/B8tN9TrSMUnGlT7JfzmPt7OAzQ5DYucSkw69SBhPiHHwMZp0/Rv3xL93UhMVfbKWniQtqHh4lwIrlDy+1n4cAdY5ohn0eVpe7Rla2Qfmymo/9d5YWzA3OlH0fmw0oFCzewbppR96IK8r7hG3EMG3xN6szqgdP+TpsRoY3fbmp+BCTw1dvQMdHDSY+68hf3NXjEkiw6KeOtXNewhI1KJnhMpe7UaYKNMdIcbg5m0Qd3P86FYd4xnApCMqaJELWrhdZb6/92EmUrsUqvuac2d5ClY5GuD2BNbDWuEe/7CwlhTXy4l6PaHA+L6KhyiCc+Ke4jI=
  file:
    - ${TRAVIS_BUILD_DIR}/build/openfiledialog*
    - ${TRAVIS_BUILD_DIR}/build/selectfolderdialog*
  skip_cleanup: true
  on:
    branch: master
