language: c
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - TARGET="linux"
  - os: osx
    osx_image: xcode8
    env:
    - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
    - TARGET="osx"
before_script:
- if [ "$TARGET" = "osx" ]; then brew update && brew install ruby && brew install
  rename; fi
- eval "${MATRIX_EVAL}"
script:
- if [ "$TARGET" = "linux" ]; then echo "===> Building for linux..." && cd "$TRAVIS_BUILD_DIR"
  && mkdir build && cd build && cmake .. && make; fi
- if [ "$TARGET" = "osx" ]; then echo "===> Building for macosx..." && cd "$TRAVIS_BUILD_DIR"
  && mkdir build && cd build && cmake .. && make; fi
- eval "rename 's/openfiledialog/openfiledialog-${TARGET}/' openfiledialog*"
- eval "rename 's/selectfolderdialog/selectfolderdialog-${TARGET}/' selectfolderdialog*"
deploy:
  provider: releases
  api_key:
    secure: tGcyXhjKd8JrIyIHRqumKnYBQxECTDLaKJ0ZcSRU93nUzvJdFKEn8LCiFTECPyyJtSG6oOTW87aIFp4DSNOnIODXiICa+mvW8dyfgnPIPoq5Xkemfxt+fTK9S4cIHi8ifouu6koJCJTEuiuOqAntnc/wuyLLPBDJnOgWa2VabmNgkkDv3XHneyyxCeZFMcrVFWsY/v60CgHBtPESxoyAc6WNvedlTbf9QlP/iy8gdYAMzXDOqDrn3QrrWMP2MVnZpo+xKztjSu31jTezvBcFZ5R0a8ftNRFyBHNJIAIdnv2idriLFt4VSjUEWPIsy8A0yqLwXSPTm91eq2Dckvv6vnaioPgt/JSvP8MVTnwYJu3ErVROoRs/DqGK6T41hnFE5lmbhLRSeMCE35e1C6TLKMdfSvW4V454JFjlLw1YUCWex6Z7v1uxDW8iXNPh+5wo5VPjnQuCCYZAk6PeHfNwfiq/Q7OUesl09nLenxi2MjjUKU9lvnUkbFguF9fWeSknw26iHOhf66UJfudnC7A04xdTcLqZceGZBJ/8Js9tR5S4ajIIGigRuTakLJ3hKA1vi2a59tLIAHDMNv8JPKlKN3oIyf8TQvMon5eiVy70x80sqiv3uJ9i8aanGMRMLmFIsLGt0bNU5cSFtVP9UfGKc1jqy9qW82oLCE8aoQ04nP0=
  file:
  - ${TRAVIS_BUILD_DIR}/build/openfiledialog*
  - ${TRAVIS_BUILD_DIR}/build/selectfolderdialog*
  skip_cleanup: true
  on:
    branch: master
